// ============================================================================
// AgentEngine — Autonomous SpecKit SDD Pipeline Agent
//
// Flow per ticket:
//   Jira poller detects new/unspecced ticket
//     → specify → clarify → plan → checklist → tasks → analyze
//     → [HUMAN GATE: CRITICAL gaps?] → implement
//     → createBranch → pushFiles → createPR
//     → commentOnJira("Spec ready + PR: [link]")
//     → WebSocket: agent_event broadcast
//
//   PR webhook events:
//     → PR comment with "regenerate tasks"  → re-run tasks step
//     → PR comment with "fix spec"          → re-run clarify step
//     → PR approved (all reviewers)          → mergePR → updateJiraStatus
// ============================================================================

import path from 'path';
import fs from 'fs';
import { runStep, SpecKitStep, STEP_OUTPUT } from './speckit-pipeline.service';
import { jiraService } from './jira.service';
import { bitbucketService } from './bitbucket.service';
import { config } from '../config';
import { getIO } from '../websocket/socket';

// ── Types ────────────────────────────────────────────────────────────────────

export type AgentStatus =
  | 'idle'
  | 'speccing'       // specify → clarify → plan → checklist → tasks
  | 'analyzing'      // analyze step
  | 'blocked'        // CRITICAL gaps found — waiting for human
  | 'implementing'   // implement step
  | 'pushing'        // branch + file commits
  | 'pr_open'        // PR created, awaiting review
  | 'merging'        // auto-merging PR
  | 'done'
  | 'error';

export interface AgentTicketState {
  ticketId: string;
  summary: string;
  assignee: string | null;
  status: AgentStatus;
  currentStep: string;
  prId?: number;
  prUrl?: string;
  branchName?: string;
  specFolder?: string;
  criticalGaps?: string[];
  log: { ts: number; message: string }[];
  startedAt: number;
  updatedAt: number;
  error?: string;
}

// In-memory registry of all tickets the agent is watching
const registry = new Map<string, AgentTicketState>();

// Tracks which ticketIds have already been processed (to avoid re-triggering)
const processedTickets = new Set<string>();

// ── Emit ─────────────────────────────────────────────────────────────────────

function emit(ticketId: string, event: string, detail?: string) {
  try {
    getIO()?.emit('agent_event', { ticketId, event, detail, ts: Date.now() });
  } catch { /* ws not ready */ }
}

function log(state: AgentTicketState, message: string) {
  state.log.push({ ts: Date.now(), message });
  state.updatedAt = Date.now();
  // Keep last 100 log entries
  if (state.log.length > 100) state.log = state.log.slice(-100);
  emit(state.ticketId, 'log', message);
  console.log(`[Vishvakarma] ${state.ticketId}: ${message}`);
}

// ── Jira comment ─────────────────────────────────────────────────────────────

async function commentOnJira(ticketId: string, body: string): Promise<void> {
  try {
    await jiraService.addComment(ticketId, body);
  } catch (err: any) {
    console.warn(`[Agent] Could not comment on Jira ${ticketId}:`, err.message);
  }
}

// ── Spec folder helpers ───────────────────────────────────────────────────────

function repoPath(): string {
  return process.env.LOCAL_REPO_PATH || config.specdev?.localRepoPath || 'D:\\repos\\tymetrix360core';
}

function slugify(text: string): string {
  return text.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 40);
}

function specFolder(ticketId: string, summary: string): string {
  return path.join(repoPath(), 'specs', `${ticketId}-${slugify(summary)}`);
}

function readFile(folder: string, relPath: string): string | null {
  const abs = path.join(folder, relPath);
  return fs.existsSync(abs) ? fs.readFileSync(abs, 'utf-8') : null;
}

function allSpecFiles(folder: string): { path: string; content: string }[] {
  const priority = ['spec.md', 'plan.md', 'tasks.md', 'analysis-report.md', 'checklists/requirements.md'];
  const results: { path: string; content: string }[] = [];

  for (const rel of priority) {
    const abs = path.join(folder, rel);
    if (fs.existsSync(abs)) {
      results.push({ path: rel, content: fs.readFileSync(abs, 'utf-8').substring(0, 10000) });
    }
  }

  // Also grab any implementation files (non-md) generated by implement step
  try {
    const impl = path.join(folder, 'implementation-notes.md');
    if (fs.existsSync(impl)) {
      results.push({ path: 'implementation-notes.md', content: fs.readFileSync(impl, 'utf-8').substring(0, 8000) });
    }
  } catch { /* skip */ }

  return results;
}

// ── Critical gap detector ─────────────────────────────────────────────────────

function extractCriticalGaps(analysisContent: string): string[] {
  const gaps: string[] = [];
  const lines = analysisContent.split('\n');
  let inCritical = false;
  for (const line of lines) {
    if (/###\s*CRITICAL/i.test(line)) { inCritical = true; continue; }
    if (/###/i.test(line) && inCritical) { inCritical = false; }
    if (inCritical && line.trim().startsWith('-') && line.trim().length > 3) {
      gaps.push(line.trim().replace(/^-\s*/, ''));
    }
  }
  return gaps;
}

// ── Main pipeline ─────────────────────────────────────────────────────────────

export async function evaluate(ticketDetail: any): Promise<void> {
  const ticketId: string = ticketDetail.key;

  // Skip if already being processed
  if (processedTickets.has(ticketId)) return;
  processedTickets.add(ticketId);

  const folder = specFolder(ticketId, ticketDetail.summary || ticketId);
  const hasSpec = fs.existsSync(path.join(folder, 'spec.md'));
  const hasTasks = fs.existsSync(path.join(folder, 'tasks.md'));

  // Already fully specced and pushed — skip
  if (hasSpec && hasTasks) {
    processedTickets.delete(ticketId); // allow re-evaluation if status changes
    return;
  }

  const state: AgentTicketState = {
    ticketId,
    summary: ticketDetail.summary || ticketId,
    assignee: ticketDetail.assignee || null,
    status: 'speccing',
    currentStep: 'specify',
    specFolder: folder,
    log: [],
    startedAt: Date.now(),
    updatedAt: Date.now(),
  };
  registry.set(ticketId, state);
  emit(ticketId, 'started', `Agent picking up ${ticketId}`);

  try {
    await runPipeline(state, ticketDetail);
  } catch (err: any) {
    state.status = 'error';
    state.error = err.message;
    log(state, `❌ Fatal: ${err.message}`);
    emit(ticketId, 'error', err.message);
  }
}

async function runPipeline(state: AgentTicketState, ticketDetail: any): Promise<void> {
  const { ticketId } = state;

  // ── Phase 1: Spec steps ─────────────────────────────────────────────
  const specSteps: SpecKitStep[] = ['specify', 'clarify', 'plan', 'checklist', 'tasks'];

  for (const step of specSteps) {
    state.currentStep = step;
    log(state, `Running /speckit.${step}…`);
    emit(ticketId, 'step_start', step);

    const result = await runStep(ticketId, step, ticketDetail);

    if (result.status === 'error') {
      state.status = 'error';
      state.error = result.error;
      log(state, `❌ ${step} failed: ${result.error}`);
      emit(ticketId, 'step_error', `${step}: ${result.error}`);
      await commentOnJira(ticketId,
        `🤖 *Vishvakarma* — Step \`/speckit.${step}\` failed:\n{code}${result.error}{code}`,
      );
      return;
    }

    log(state, `✅ ${step} done → ${STEP_OUTPUT[step]}`);
    emit(ticketId, 'step_done', step);
  }

  // ── Phase 2: Analyze ────────────────────────────────────────────────
  state.status = 'analyzing';
  state.currentStep = 'analyze';
  log(state, 'Running /speckit.analyze…');

  const analyzeResult = await runStep(ticketId, 'analyze', ticketDetail);

  if (analyzeResult.status === 'error') {
    state.status = 'error';
    state.error = analyzeResult.error;
    log(state, `❌ analyze failed: ${analyzeResult.error}`);
    return;
  }

  // Check for CRITICAL gaps
  const analysisContent = analyzeResult.output || '';
  const criticalGaps = extractCriticalGaps(analysisContent);

  if (criticalGaps.length > 0) {
    state.status = 'blocked';
    state.criticalGaps = criticalGaps;
    log(state, `⚠️ Blocked — ${criticalGaps.length} CRITICAL gap(s) found`);
    emit(ticketId, 'blocked', criticalGaps.join(' | '));

    const gapList = criticalGaps.map(g => `* ${g}`).join('\n');
    await commentOnJira(ticketId,
      `🤖 *Vishvakarma* — Analysis found *${criticalGaps.length} CRITICAL gap(s)* that must be resolved before implementation:\n\n${gapList}\n\nPlease update the ticket description/ACs and Vishvakarma will retry.`,
    );
    // Don't delete from processedTickets — will stay blocked until manually re-triggered
    return;
  }

  log(state, '✅ analyze passed — no critical gaps');

  // ── Phase 3: Implement ───────────────────────────────────────────────
  state.status = 'implementing';
  state.currentStep = 'implement';
  log(state, 'Running /speckit.implement…');

  const implResult = await runStep(ticketId, 'implement', ticketDetail);

  if (implResult.status === 'error') {
    state.status = 'error';
    state.error = implResult.error;
    log(state, `❌ implement failed: ${implResult.error}`);
    return;
  }

  log(state, '✅ implement done — scaffold files generated');

  // ── Phase 4: Branch + Push ───────────────────────────────────────────
  state.status = 'pushing';
  state.currentStep = 'push';

  const branchName = `feature/${ticketId.toLowerCase()}-speckit`;
  state.branchName = branchName;
  log(state, `Creating branch: ${branchName}`);

  const defaultBranch = await bitbucketService.getDefaultBranch();
  const branch = await bitbucketService.createBranch(branchName, defaultBranch);

  if (!branch) {
    log(state, '⚠️ Branch creation failed — may already exist, continuing');
  } else {
    log(state, `✅ Branch ready: ${branch.name}`);
  }

  // Push all spec + generated files
  const files = allSpecFiles(state.specFolder!);
  let pushed = 0;

  for (const file of files) {
    const commitMsg = `[${ticketId}] SpecKit: ${file.path}`;
    const ok = await bitbucketService.commitFileToBranch(branchName, `specs/${ticketId.toLowerCase()}-speckit/${file.path}`, file.content, commitMsg);
    if (ok) {
      pushed++;
      log(state, `  pushed: ${file.path}`);
    } else {
      log(state, `  ⚠️ failed to push: ${file.path}`);
    }
  }

  log(state, `✅ Pushed ${pushed}/${files.length} files to ${branchName}`);

  // ── Phase 5: Create PR ───────────────────────────────────────────────
  state.currentStep = 'createPR';
  const specContent = readFile(state.specFolder!, 'spec.md') || '';
  const tasksContent = readFile(state.specFolder!, 'tasks.md') || '';

  // Count tasks
  const taskCount = (tasksContent.match(/- \[ \]/g) || []).length;

  const prDescription = [
    `## 🤖 SpecKit Auto-Generated Scaffold`,
    ``,
    `**Ticket:** [${ticketId}] ${state.summary}`,
    `**Assignee:** ${state.assignee || 'Unassigned'}`,
    `**Generated by:** SpecKit SDD Agent`,
    ``,
    `### What's in this PR`,
    `- \`spec.md\` — Feature specification with user stories + ACs`,
    `- \`plan.md\` — Technical design: data model, API contracts, phases`,
    `- \`checklists/requirements.md\` — Requirements quality checklist`,
    `- \`tasks.md\` — ${taskCount} implementation tasks (ordered, parallelizable)`,
    `- \`analysis-report.md\` — Coverage matrix + readiness score`,
    `- \`implementation-notes.md\` — AI-generated scaffold files`,
    ``,
    `### Spec Overview`,
    specContent.split('\n').slice(0, 20).join('\n'),
  ].join('\n');

  const pr = await bitbucketService.createPullRequest({
    title: `[${ticketId}] ${state.summary} — SpecKit scaffold`,
    description: prDescription,
    sourceBranch: branchName,
    targetBranch: defaultBranch,
    reviewers: state.assignee ? [state.assignee] : [],
  });

  if (pr) {
    state.prId = pr.id;
    state.prUrl = pr.url;
    state.status = 'pr_open';
    log(state, `✅ PR #${pr.id} created: ${pr.url}`);
    emit(ticketId, 'pr_created', pr.url);
  } else {
    state.status = 'pr_open';
    log(state, '⚠️ PR creation failed — files pushed but no PR');
  }

  // ── Phase 6: Comment on Jira ─────────────────────────────────────────
  const prLink = state.prUrl || '(PR creation failed — check Bitbucket)';
  await commentOnJira(ticketId,
    `🤖 *Vishvakarma* completed the full SDD pipeline for this ticket.\n\n` +
    `*PR:* ${prLink}\n` +
    `*Branch:* \`${branchName}\`\n` +
    `*Files pushed:* ${pushed}\n` +
    `*Tasks generated:* ${taskCount}\n\n` +
    `_Reply on the PR with "regenerate tasks" or "fix spec" to trigger re-runs._`,
  );

  log(state, `🎉 Pipeline complete for ${ticketId}`);
  emit(ticketId, 'complete', `PR: ${prLink}`);
}

// ── PR webhook handler ────────────────────────────────────────────────────────

export async function handlePREvent(event: {
  action: string;
  prId: number;
  comment?: string;
  approvalCount?: number;
  requiredApprovals?: number;
}): Promise<void> {
  // Find which ticket this PR belongs to
  const state = [...registry.values()].find(s => s.prId === event.prId);
  if (!state) return;

  const { ticketId } = state;

  // PR comment triggers
  if (event.action === 'comment' && event.comment) {
    const lower = event.comment.toLowerCase();

    if (lower.includes('regenerate tasks')) {
      log(state, `🔄 PR comment triggered: regenerate tasks`);
      emit(ticketId, 'retriggered', 'tasks');

      const detail = await jiraService.getIssueDetail(ticketId);
      if (!detail) return;

      const result = await runStep(ticketId, 'tasks', detail);
      if (result.status === 'done') {
        const tasksContent = readFile(state.specFolder!, 'tasks.md') || '';
        await bitbucketService.commitFileToBranch(
          state.branchName!,
          `specs/${ticketId.toLowerCase()}-speckit/tasks.md`,
          tasksContent,
          `[${ticketId}] Regenerate tasks.md via PR comment`,
        );
        log(state, '✅ tasks.md regenerated and pushed');
      }
    }

    if (lower.includes('fix spec')) {
      log(state, `🔄 PR comment triggered: fix spec (re-running clarify)`);
      emit(ticketId, 'retriggered', 'clarify');

      const detail = await jiraService.getIssueDetail(ticketId);
      if (!detail) return;

      const result = await runStep(ticketId, 'clarify', detail);
      if (result.status === 'done') {
        const specContent = readFile(state.specFolder!, 'spec.md') || '';
        await bitbucketService.commitFileToBranch(
          state.branchName!,
          `specs/${ticketId.toLowerCase()}-speckit/spec.md`,
          specContent,
          `[${ticketId}] Update spec.md via PR comment`,
        );
        log(state, '✅ spec.md clarified and pushed');
      }
    }
  }

  // Auto-merge when all required approvals met
  if (event.action === 'approved') {
    const required = event.requiredApprovals ?? 1;
    const current = event.approvalCount ?? 0;

    if (current >= required && state.prId) {
      state.status = 'merging';
      log(state, `🔀 All ${required} approval(s) received — auto-merging PR #${state.prId}`);
      emit(ticketId, 'merging', `PR #${state.prId}`);

      const merged = await mergePR(state.prId);
      if (merged) {
        state.status = 'done';
        log(state, `✅ PR #${state.prId} merged — updating Jira status`);
        emit(ticketId, 'merged', `PR #${state.prId}`);

        await commentOnJira(ticketId,
          `🤖 *Vishvakarma* — PR #${state.prId} merged successfully. Branch \`${state.branchName}\` deleted.\n\n_Moving ticket status → Ready for QA._`,
        );

        await jiraService.transitionIssue(ticketId, 'Ready for QA');
      } else {
        log(state, `⚠️ Auto-merge failed for PR #${state.prId} — manual merge required`);
        emit(ticketId, 'merge_failed', `PR #${state.prId}`);
      }
    }
  }
}

// ── PR merge ──────────────────────────────────────────────────────────────────

async function mergePR(prId: number): Promise<boolean> {
  try {
    const project = config.bitbucket.projectKey;
    const repo = config.bitbucket.defaultRepo;
    // @ts-ignore — accessing internal client via service (acceptable for internal tooling)
    const client = (bitbucketService as any).client;
    await client.post(
      `/projects/${project}/repos/${repo}/pull-requests/${prId}/merge`,
      { version: -1 }, // -1 = latest version
    );
    return true;
  } catch (err: any) {
    console.error('[Agent] PR merge failed:', err.response?.status, err.message);
    return false;
  }
}

// ── Registry accessors ────────────────────────────────────────────────────────

export function getAgentState(ticketId: string): AgentTicketState | null {
  return registry.get(ticketId.toUpperCase()) || null;
}

export function getAllAgentStates(): AgentTicketState[] {
  return [...registry.values()].sort((a, b) => b.updatedAt - a.updatedAt);
}

export function retryBlocked(ticketId: string): boolean {
  const state = registry.get(ticketId.toUpperCase());
  if (!state || state.status !== 'blocked') return false;
  state.status = 'speccing';
  state.criticalGaps = [];
  processedTickets.delete(ticketId.toUpperCase());
  return true;
}

export function isProcessed(ticketId: string): boolean {
  return processedTickets.has(ticketId.toUpperCase());
}

export function resetTicket(ticketId: string): void {
  processedTickets.delete(ticketId.toUpperCase());
  registry.delete(ticketId.toUpperCase());
}
